//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagementWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class empDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empDetail()
        {
            this.leaveEntries = new HashSet<leaveEntry>();
        }
    
        public int empCode { get; set; }
        public string empName { get; set; }
        public string supervisorName { get; set; }
        public string leavePackage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leaveEntry> leaveEntries { get; set; }
    }
}
