//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagementWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaveEntry
    {
        public int empCode { get; set; }
        public int leaveType { get; set; }
        public Nullable<System.DateTime> requestedDate { get; set; }
        public Nullable<System.DateTime> approvedDate { get; set; }
        public string supervisorName { get; set; }
        public string currentStatus { get; set; }
        public string empComments { get; set; }
        public string supervisorComments { get; set; }
    
        public virtual empDetail empDetail { get; set; }
    }
}
