//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagementWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaveType
    {
        public int typeCode { get; set; }
        public string leaveDescription { get; set; }
    }
}
